In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

import mlflow

C:\Users\Madhu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
prophet_df = pd.read_csv(
    "../data/processed/sales_forecast.csv"
)

prophet_df.head()

           ds          yhat    yhat_lower    yhat_upper
0  2009-12-01  56388.633212  40938.080950  71852.147689
1  2009-12-02  53943.073819  38541.525653  70483.776354
2  2009-12-03  61071.679344  45166.886353  77673.725952
3  2009-12-04  51095.579199  35243.865377  67046.029075
4  2009-12-05   9529.931498  -7177.457581  26059.781353

In [3]:
lstm_df = pd.read_csv(
    "../data/processed/lstm_forecast.csv"
)

lstm_df.head()

     Actual  Predicted
0  54198.37  23900.797
1  17240.61  28173.322
2  33393.29  26444.152
3  19808.40  27390.066
4  20277.05  26231.467

In [4]:
actual = lstm_df["Actual"]
predicted = lstm_df["Predicted"]

lstm_mae = mean_absolute_error(
    actual,
    predicted
)

lstm_rmse = np.sqrt(
    mean_squared_error(
        actual,
        predicted
    )
)

print("MAE :", lstm_mae)
print("RMSE:", lstm_rmse)

MAE : 14078.198704347822
RMSE: 21727.12027278423

In [5]:
with mlflow.start_run(run_name="LSTM_Forecast"):

    mlflow.log_param("Model", "LSTM")

    mlflow.log_metric("MAE", lstm_mae)
    mlflow.log_metric("RMSE", lstm_rmse)

print("LSTM metrics logged successfully!")

2026/06/08 11:28:15 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/06/08 11:28:15 INFO mlflow.store.db.utils: Updating database tables

LSTM metrics logged successfully!